
export const GET_CITY_BY_COUNTRY = 'GET_CITY_BY_COUNTRY';
export const GET_CITY_BY_COUNTRY_SUCCESS = 'GET_CITY_BY_COUNTRY_SUCCESS';
export const GET_WEATHER_BY_CITY = 'GET_WEATHER_BY_CITY';
export const GET_WEATHER_BY_CITY_SUCCESS = 'GET_WEATHER_BY_CITY_SUCCESS';
